format_version: 10

pipelines:
  say-hi:
    group: movies
    materials:
      repo:
        git: https://github.com/manav11vanam/sample-pipelines.git
        branch: main
        shallow_clone: true

    stages:
    - build:
        jobs:
          build:
            elastic_profile_id: demo-app
            tasks:
            - script: ./run.sh one

  say-hi-manual:
    group: movies
    materials:
      repo:
        git: https://github.com/manav11vanam/sample-pipelines.git
        branch: main

    stages:
    - build:
        approval: manual
        jobs:
          build:
            elastic_profile_id: demo-app
            tasks:
            - script: ./run.sh two
