format_version: 4

pipelines:
  say-hi:
    group: movies
    label_template: ${git[:7]}
    materials:
      git:
        git: https://github.com/manav11vanam/sample-pipelines.git
        branch: main
        shallow_clone: true

    stages:
    - build:
        jobs:
          build:
            elastic_profile_id: demo-app
            tasks:
            - exec:
                command: bash
                arguments:
                - ./gocd/scripts/run.sh
                - one

  say-hi-manual:
    group: movies
    label_template: ${git[:7]}
    materials:
      git:
        git: https://github.com/manav11vanam/sample-pipelines.git
        branch: main

    stages:
    - build:
        approval: manual
        jobs:
          build:
            elastic_profile_id: demo-app
            tasks:
            - exec:
                command: bash
                arguments:
                - ./gocd/scripts/run.sh
                - two
