format_version: 4

pipelines:
  git-writer-test-ssh:
    group: dummy-app
    label_template: ${git[:7]}

    materials:
      git:
        git: git@github.com:manav11vanam/sample-pipelines.git
        branch: main

    stages:
    - bump-version:
        clean_workspace: true
        jobs:
          edit-file:
            elastic_profile_id: k8s-ssh-agent
            tasks:
            - exec:
                command: /bin/sh
                arguments:
                - -c
                - |
                  set -e

                  echo "Before:"
                  cat argocd/dummy-app/version.txt

                  echo "version=$(date +%s)" > argocd/dummy-app/version.txt

                  git config user.email "gocd@local"
                  git config user.name "GoCD"

                  git add argocd/dummy-app/version.txt
                  git commit -m "chore: bump dummy app version" || echo "Nothing to commit"

                  git push origin main
